teams:
  - name: teamA
    repoOrg: jyepesr1
    scmCredentialsID: ""
    projects:
      - name: test1
        repo: jenkins-test
        numJobsToKeep: 10
        daysToKeepJobs: 10

      - name: test2
        repo: jenkins-test
        numJobsToKeep: 10
        daysToKeepJobs: 10
        